export const questions = {
  en: [
    "What is your name?",
    "What is your favorite animal?",
    "What is your favorite season?",
    "When you were a child, where did you want to explore?",
    "What do you want to do on your day off?",
    "What kind of view do you want to see when you open the window in the morning on a trip?",
    "When do you feel calm?",
    "What do you want to do or like to do in this list?",
  ],
  jp: [
    "あなたの名前はなんですか？",
    "好きな動物はなんですか？",
    "好きな季節はなんですか？",
    "子供の頃、探検したいと思った場所は？",
    "休みの日には何をしたい？",
    "旅行先での朝、窓を開けた時に見たい景色はどんなもの？",
    "落ち着くのはどんなとき？",
    "この中でやってみたい、好きなことはなんですか？",
  ],
};

export const questionSummary = {
  en: [
    "Your Name",
    "Favorite Animal",
    "Favorite Season",
    "Childhood Exploration",
    "Day Off Activity",
    "Morning View",
    "Calm Moment",
    "Favorite Activity",
  ],
  jp: [
    "名前",
    "好きな動物",
    "好きな季節",
    "子供の頃の探検",
    "休日の過ごし方",
    "朝の景色",
    "落ち着く瞬間",
    "好きなこと",
  ],
};

export const options = {
  en: [
    [""],
    ["Dog", "Cat", "Panda", "Rabbit", "Fish", "Bird", "Hamster"],
    ["Spring", "Summer", "Autumn", "Winter"],
    [
      "Magical Wonderland",
      "Game World",
      "Inside a Castle",
      "Secret Forest",
      "Cave",
      "Back of the Moon",
      "Rooftop of a Building",
      "Coral Reef",
    ],
    [
      "Reading",
      "Napping",
      "Walking",
      "Traveling",
      "Baking",
      "Watching Videos/Movies",
      "Drawing",
    ],
    [
      "Blue Sky and Morning Sun",
      "Mountain Wrapped in Mist",
      "Forest in Light Rain",
      "Snowy Scenery",
      "Dawn with Stars Still Remaining",
    ],
    [
      "When Listening to Music",
      "When Walking Alone",
      "When Immersed in a Hobby",
      "When Taking a Bath",
      "Before Going to Bed",
      "When Spending Time with Family",
      "When Spending Time with Friends/Partner",
      "When Cooking",
    ],
    [
      "Scuba Diving",
      "Space Travel",
      "Leisurely Yachting",
      "Mountain Climbing",
      "Cafe Hopping",
    ],
  ],
  jp: [
    [""],
    ["犬", "猫", "パンダ", "うさぎ", "魚", "鳥", "ハムスター"],
    ["春", "夏", "秋", "冬"],
    [
      "おとぎの国",
      "ゲームの世界",
      "お城の中",
      "秘密の森",
      "洞窟",
      "月の裏側",
      "ビルの屋上",
      "珊瑚礁",
    ],
    [
      "読書",
      "昼寝",
      "散歩",
      "旅行",
      "お菓子作り",
      "動画・映画鑑賞",
      "お絵描き",
    ],
    [
      "青空と朝日",
      "霧に包まれた山",
      "小雨の森",
      "雪景色",
      "星がまだ残る夜明け",
    ],
    [
      "音楽を聴く時",
      "一人で散歩している時",
      "趣味に没頭している時",
      "お風呂に入っている時",
      "寝る前",
      "家族と過ごす時",
      "友達・恋人と過ごす時",
      "料理をしている時",
    ],
    [
      "スキューバダイビング",
      "宇宙旅行",
      "ヨットでのんびり",
      "登山",
      "カフェ巡り",
    ],
  ],
};
